### PR TITLE
[BPK-4129] Add social meta

### PR DESCRIPTION
**Pull request by georgegillams**

### CODE REVIEW

**Comment by georgegillams** [comment]
> Is this WIP or ready for review? If WIP, please label it

Just needs design review

**Comment by shaundon** [comment]
I mean this in the nicest way possible, but you've just repeated what the label said 😂 

Are you actively in the process of getting a design review? If not, I would argue that it's still WIP as it's not mergeable

**Comment by georgegillams** [comment]
> I mean this in the nicest way possible, but you've just repeated what the label said 😂
> 
> Are you actively in the process of getting a design review? If not, I would argue that it's still WIP as it's not mergeable

tbh I think it can just be reviewed, and we can iterate on the design later if we see fit. Mainly saying that as it's hard to see how these values will appear on social platforms until they're live

**Review by shaundon — APPROVED** [review]

**Comment by shaundon** [comment]
Yeah I agree. I think it's also fine for us to do the 'ask forgiveness over permission' thing with design decisions like this. We don't want to have to ask Dima for everything, so as long as we make sensible choices that follow the brand guidelines (as you have here) we can default to assuming it's ok.

**Pull request merged**
