### PR TITLE
[BD-6212]update bpk-component-badge page

### PR DESCRIPTION
**Pull request by giriawu**
Figma: https://www.figma.com/file/irZ3YBx8vOm16ICkAr7mB3/Backpack?node-id=6099%3A2722

In the new design of the hotel card, we have made extensive use of `BpkBadge` which is white color on a black background.
But this theme style is not yet well supported on the web (they are already supported on iOs and Android).
So we added it to `bpk-component-badge` as the base theme - **strong**, for better consistency support and user experience.

Related PR in backpack-foundations: https://github.com/Skyscanner/backpack-foundations/pull/106
Related PR in backpack: https://github.com/Skyscanner/backpack/pull/2532

## Snapshot
image

Remember to include the following changes:
+ [x] [Links platform metadata](https://github.com/Skyscanner/backpack-docs/blob/main/docs/src/layouts/links.js) - https://backpack.github.io/components/badge/?platform=web

### CODE REVIEW

**Comment by giriawu** [comment]
Will update after this [PR](https://github.com/Skyscanner/backpack/pull/2532) in backpack is merged.

**Review by jasonhuang-sky — DISMISSED** [review]

**Review by Supremeyh — APPROVED** [review]
lgtm

**Comment by giriawu** [comment]
Hi backpack team, feel free to merge this PR when you have time, thank you very much!

**Review by gert-janvercauteren — APPROVED** [review]
LGTM!

**Pull request merged**
