### PR TITLE
[NO-JIRA] Markdown alternating sections

### PR DESCRIPTION
**Pull request by georgegillams**
Did this mostly for fun, and not for profit 😂

I think we decided this was yagni, but I wanted the challenge 🤪

It should only be needed in this one place, so I think the work to maintain this going forward will be minimal.

Screenshot_2020-10-28 Backpack Status Backpack(1)

### CODE REVIEW

**Comment by shaundon** [comment]
thanks i hate it

**Comment by shaundon** [comment]
This does look good but my rationale from the other day hasn't changed:

I said we probably could reinstate the alternating sections but it would be hacky and increase maintenance burden. This is hacky and increases the maintenance burden.

Also, it's a documentation website, it doesn't need to be this stylised. It *should* have a simple design.

**Review by olliecurtis — COMMENTED** [review]
LGTM - Just gonna run it locally

**Comment by georgegillams** [comment]
> LGTM - Just gonna run it locally

See @shaundon's comment above ;)

**Comment by georgegillams** [comment]
Killing this as it's YAGNI

**Pull request closed without merging**
